# Generated by Django 2.2.10 on 2020-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TS', 'TShirt'), ('SW', 'Sport wear'), ('CW', 'Casual wear'), ('DM', 'designer masks'), ('PPE', 'PPE kits')], max_length=3)),
                ('typechoice', models.CharField(choices=[('TS', 'Track suits'), ('L', 'Lowers'), ('S', 'Shorts'), ('CTS', 'Cotton t-shirt'), ('STS', 'Sublimation t-shirt'), ('ML', 'Mask for ladies'), ('MM', 'Mask for men'), ('MU', 'Medical Use')], max_length=3)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
