# Generated by Django 2.2.10 on 2020-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200629_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TShirt', 'TShirt'), ('Sport Wear', 'Sport wear'), ('Casual Wear', 'Casual wear'), ('Designer Masks', 'designer masks'), ('PPE kits', 'PPE kits')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='typechoice',
            field=models.CharField(choices=[('Track Suit', 'Track suits'), ('Lowers', 'Lowers'), ('Shorts', 'Shorts'), ('Cotton T-Shirt', 'Cotton t-shirt'), ('Sublimation T-Shirt', 'Sublimation t-shirt'), ('Mask for Ladies', 'Mask for ladies'), ('Mask for Men', 'Mask for men'), ('Medical Use', 'Medical Use')], max_length=50),
        ),
    ]
