# Generated by Django 2.2.10 on 2020-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200630_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='message',
            field=models.TextField(),
        ),
    ]
