# Generated by Django 2.2.10 on 2020-06-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200630_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='xl', max_length=255),
        ),
    ]
