# Generated by Django 2.2.10 on 2020-06-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200701_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
