# Generated by Django 2.2.10 on 2020-06-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200701_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
